### PR TITLE
AppleSite content

### PR DESCRIPTION
**Pull request by tzvaita**
Site finished.

### CODE REVIEW

**Review by Forison — COMMENTED** [review]
#### Pull request under review by Addo

**Review by Forison — CHANGES_REQUESTED** [review]
# Good job @tzvaita,
The project looks great.🙂
Here are two tinny changes we have to make to get the project approved.🙂
* [ ]  Files not related to the project should not be committed and added to .gitignore.
please remove ```.editorconfig``` or create a ```.gitignore``` file and store the path there so it does not get committed.🙂
* [ ] Let us use this opportunity to improve our semantic Html by wrapping ```.main-area```  in ```main``` tag🙂
## Kindly make these changes and submit the project for review🙂
Feel free to contact me on [LinkedIn](https://www.linkedin.com/in/forison-addo-558201159/), [Twitter](https://twitter.com/ADDOBOAKYE1) or slack for further clarification if necessary. I would be happy to assist you.
#### Happy coding😇

**Comment by tzvaita** [comment]
Done with review recommendations.

**Review by Forison — COMMENTED** [review]
#### Pull request under review by Addo

**Review by Forison — APPROVED** [review]
# Good job @tzvaita,🙂
You have successfully implemented the changes🙂
## Project is approved💪 
- Kindly take note of this
> This is how to handle the .gitignore file. The path of the file we want to use in our project but don't want to commit have their path written in gitignore, so that when you push those files, they don't get into your repo as other vital files(for instance the path of.editorconfig path should be in the gitignore) in this case there is no point having a gitignore file that is empty. It serves no purpose.
### Please take note of this info, You may contact me for further clarification on slack or LinkedIn🙂
#### happy coding🙂

**Comment by tzvaita** [comment]
thanks about the gitignore. i was actually having trouble finding out how
do i add the files to it. Thanks

**Pull request merged**
